spring.application.name=foro
spring.datasource.url=jdbc:mysql://localhost/foro
spring.datasource.username=root
spring.datasource.password=M4ncH1t45.

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:clave_por_defecto_321}